openapi: 3.0.0
servers:
    -
        url: 'https://algorithmia.com/v1/algo/'
info:
    title: DeepFilter
    description: 'Apply artistic and stylish filters to your images'
    version: 0.6.0
    license:
        name: apl
paths:
    /deeplearning/DeepFilter/0.6.0:
        post:
            summary: 'Run DeepFilter'
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                images:
                                    type: array
                                    items:
                                        type: string
                                savePaths:
                                    type: array
                                    items:
                                        type: string
                                filterName:
                                    type: string
                        example:
                            images:
                                - 'data://deeplearning/example_data/elon_musk.jpg'
                            savePaths:
                                - 'data://.algo/deeplearning/DeepFilter/temp/elon_space_pizza.jpg'
                            filterName: space_pizza
            responses:
                '200':
                    description: 'Algorithm Success'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    savePaths:
                                        type: array
                                        items:
                                            type: string
                            example:
                                savePaths:
                                    - 'data://.algo/deeplearning/DeepFilter/temp/elon_space_pizza.jpg'
