openapi: 3.0.0
servers:
    -
        url: 'https://algorithmia.com/v1/algo/'
info:
    title: 'Document Classifier'
    description: 'Classify or Recommend documents with ease'
    version: 1.1.1
    license:
        name: apl
paths:
    /nlp/DocumentClassifier/1.1.1:
        post:
            summary: 'Run DocumentClassifier'
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                data:
                                    type: array
                                    items:
                                        type: object
                                        properties:
                                            text:
                                                type: string
                                namespace:
                                    type: string
                                mode:
                                    type: string
                                option:
                                    type: string
                                returnDocs:
                                    type: boolean
                        example:
                            data:
                                -
                                    text: 'The atomic nucleus is held together with the strong nuclear force. Nuclear power is a very economical fuel source for today''s economies.'
                            namespace: 'data://nlp/arxiv_model'
                            mode: predict
                            option: 'very accurate'
                            returnDocs: true
            responses:
                '200':
                    description: 'Algorithm Success'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    predictions:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                specimen:
                                                    type: string
                                                topN:
                                                    type: array
                                                    items:
                                                        type: object
                                                        properties:
                                                            distance:
                                                                type: number
                                                            prediction:
                                                                type: string
                                                            text:
                                                                type: string
                                                        required:
                                                            - distance
                                                            - prediction
                                                            - text
                            example:
                                predictions:
                                    -
                                        specimen: 'The atomic nucleus is held together with the strong nuclear force. Nuclear power is a very economical fuel source for today''s economies.'
                                        topN:
                                            -
                                                distance: 0.05968642234802246
                                                prediction: economics
                                                text: 'Humankind is confronted with a nuclear stewardship curse, facing the prospect of needing to manage nuclear products over long time scales in the face of the short-time scales of human polities. I propose a super Manhattan-type effort to rejuvenate the nuclear energy industry to overcome the current dead-end in which it finds itself, and by force, humankind has trapped itself in. A 1% GDP investment over a decade in the main nuclear countries could boost economic growth with a focus on the real world, epitomised by nuclear physics chemistry engineering economics with well defined targets. By investing vigorously to obtain scientific and technological breakthroughs, we can create the spring of a world economic rebound based on new ways of exploiting nuclear energy, both more safely and more durably.'
                                            -
                                                distance: 0.08835440874099731
                                                prediction: nuclear
                                                text: 'A global analysis of nuclear medium modifications of parton distributions is presented using deeply inelastic scattering data of various nuclear targets. Two obtained data sets are provided for quark and gluon nuclear modification factors, referred as nIMParton16. One is from the global fit only to the experimental data of isospin-scalar nuclei (Set A), and the other is from the fit to all the measured nuclear data (Set B). The scale-dependence is described by DGLAP equations with nonlinear corrections in this work. The Fermi motion and off-shell effect, nucleon swelling, and parton-parton recombination are taken into account together for modeling the complicated $x$-dependence of nuclear modification. The nuclear gluon shadowing in this paper is dynamically generated by the QCD evolution of parton splitting and recombination processes with zero gluon density at the input scale. Sophisticated nuclear dependence of nuclear medium effects is studied with only two free parameters. With the obtained free parameters from the global analysis, the nuclear modifications of parton distribution functions of unmeasured nuclei can be predicted in our model. Nuclear modification of deuteron is also predicted and shown with recent measurement at JLab.'
                                            -
                                                distance: 0.23754829168319705
                                                prediction: electron
                                                text: 'We have explored the manifold physical scenario emerging from a model of Dynamic Nuclear Polarization (DNP) via thermal mixing under the hypothesis of highly effective electron-electron interaction. When the electron and nuclear reservoirs are also assumed to be in strong thermal contact and the microwave irradiation saturates the target electron transition, the enhancement of the nuclear polarization is expected to be considerably high even if the irradiation frequency is set far away from the centre of the ESR line (as already observed by Borghini) and the typical polarization time is reduced on moving towards the boundaries of said line. More reasonable behaviours are obtained by reducing the level of microwave saturation or the contact between electrons and nuclei in presence of nuclear leakage. In both cases the function describing the dependency of the steady state nuclear polarization on the frequency of irradiation becomes sharper at the edges and the build up rate decreases on moving off-resonance. If qualitatively similar in terms of the effects produced on nuclear polarization, the degree of microwave saturation and of electron-nucleus contact has a totally different impact on electron polarization, which is of course strongly correlated to the effectiveness of saturation and almost insensitive, at the steady state, to the magnitude of the interactions between the two spin reservoirs. The likelihood of the different scenario is discussed in the light of the experimental data currently available in literature, to point out which aspects are suitably accounted and which are not by the declinations of thermal mixing DNP considered here.'
                                            -
                                                distance: 0.41273558139801025
                                                prediction: learning
                                                text: 'Recently, model-free reinforcement learning algorithms have been shown to solve challenging problems by learning from extensive interaction with the environment. A significant issue with transferring this success to the robotics domain is that interaction with the real world is costly, but training on limited experience is prone to overfitting. We present a method for learning to navigate, to a fixed goal and in a known environment, on a mobile robot. The robot leverages an interactive world model built from a single traversal of the environment, a pre-trained visual feature encoder, and stochastic environmental augmentation, to demonstrate successful zero-shot transfer under real-world environmental variations without fine-tuning.'
