openapi: 3.0.0
servers:
    -
        url: 'https://algorithmia.com/v1/algo/'
info:
    title: 'scraglehtml - HTML of javascript based web page'
    description: 'scraglehtml load given web page, scroll down a number of times and wait until javascript loaded, then save HTML.'
    version: 0.1.3
    license:
        name: apl
paths:
    /progragle/scraglehtml/0.1.3:
        post:
            summary: 'Run scraglehtml'
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                url:
                                    type: string
                                scroll:
                                    type: number
                                injectJsFile:
                                    type: string
                        example:
                            url: 'https://www.huffingtonpost.com/entry/apple-new-iphone-x_us_59b809f9e4b027c149e2dbe0'
                            scroll: 5
                            injectJsFile: 'data://progragle/public/scraglehtml-inject.js'
            responses:
                '200':
                    description: 'Algorithm Success'
                    content:
                        schema:
                            text/plain:
                                type: string
                        example: '"{\"isError\":false,\"errorMessage\":\"Getting HTML is completed successfully!\",\"errorCode\":\"Success\",\"results\":{\"outputFile\":\"data://.algo/progragle/scraglehtml/temp/a626df0a4fd04f29872a738a05b67fd8.html\",\"injectJsFileUrl\":\"https://algorithmia.com/v1/data/progragle%2Fpublic%2Fscraglehtml-inject.js\",\"errorStream\":\"\",\"outputFileUrl\":\"https://algorithmia.com/v1/data/.algo%2Fprogragle%2Fscraglehtml%2Ftemp%2Fa626df0a4fd04f29872a738a05b67fd8.html\",\"scroll\":5,\"injectJsFile\":\"data://progragle/public/scraglehtml-inject.js\",\"outputStream\":\"\",\"cookiesFile\":\"data://.algo/progragle/scraglehtml/temp/63c131bbc5414cd38aeea01dc87201b3.cookies\",\"cookiesFileUrl\":\"https://algorithmia.com/v1/data/.algo%2Fprogragle%2Fscraglehtml%2Ftemp%2F63c131bbc5414cd38aeea01dc87201b3.cookies\"}}"'
