openapi: 3.0.0
servers:
    -
        url: 'https://algorithmia.com/v1/algo/'
info:
    title: Summarizer
    description: 'Advanced Content Summarizer'
    version: 0.1.3
    license:
        name: apl
paths:
    /SummarAI/Summarizer/0.1.3:
        post:
            summary: 'Run Summarizer'
            requestBody:
                content:
                    schema:
                        text/plain:
                            type: string
                    example: '"We live in the computer age, a world increasingly shaped by programmers. Who are they, what motivates them, and what impact will they have on the rest of us?\nThat impact is ever more visible. Everything around us is becoming computerized. Your typewriter is gone, replaced by a computer. Your phone has turned into a computer. So has your camera. Soon your TV and VCR will be components in a computer network. Your car has more processing power in it than a room-sized mainframe did in 1970. Letters, encyclopedias, newspapers, and even your local store are being replaced by the Internet. What''s next?\nHackers & Painters examines the world of hackers and the motivations of the people who occupy it. In clear, thoughtful prose that draws on illuminating historical examples, Graham takes readers on a fast-moving tour of what he calls an intellectual Wild West.\nWhy do kids who can''t master high school end up as some of the most powerful people in the world? What makes a startup succeed? Will technology create a gap between those who understand it and those who don''t? Will Microsoft take over the Internet? What to do about spam?\nIf you want to understand what hackers are up to, this book will tell you. And if you are a hacker, you''ll probably recognize in it a portrait of yourself."'
            responses:
                '200':
                    description: 'Algorithm Success'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    summarized_data:
                                        type: string
                                    auto_gen_ranked_keywords:
                                        type: array
                                        items:
                                            type: string
                            example:
                                summarized_data: 'Letters, encyclopedias, newspapers, and even your local store are being replaced by the Internet...We live in the computer age, a world increasingly shaped by programmers...'
                                auto_gen_ranked_keywords:
                                    - impact
                                    - encyclopedia
                                    - mainframe
                                    - motivate
                                    - vcr
                                    - programmer
                                    - newspaper
                                    - age
                                    - typewriter
                                    - letter
                                    - increasingly
                                    - internet
                                    - room-sized
                                    - camera
                                    - network
                                    - phone
                                    - turned
                                    - tv
                                    - store
                                    - power
                                    - shaped
                                    - hacker
                                    - car
                                    - visible
