openapi: 3.0.0
servers:
    -
        url: 'https://algorithmia.com/v1/algo/'
info:
    title: Autocorrelate
    description: 'Finds the dataset’s cross-correlation with itself'
    version: 0.2.0
    license:
        name: apl
paths:
    /TimeSeries/Autocorrelate/0.2.0:
        post:
            summary: 'Run Autocorrelate'
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                type: number
                        example:
                            - 1
                            - 2
                            - 3
                            - 4
                            - 2
                            - 3
                            - 4
                            - 5
                            - 3
                            - 4
                            - 5
                            - 5
            responses:
                '200':
                    description: 'Algorithm Success'
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: number
                            example:
                                - 159
                                - 143
                                - 134
                                - 137
                                - 149
                                - 134
                                - 128
                                - 134
                                - 149
                                - 137
                                - 134
                                - 143
